spring:
  datasource:
    url: jdbc:h2:file:./data/librarydb;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: mappings
app:
  jwt:
    secret: "zpGOf8kzDj3Txo2UO9FzgS0Y8pd6YLiramaHLPtJ0sZNA/0gnMSuXLpsn6cdZkBKz8BJVuaRRjOUS2MmRnzUWg=="
    expires-in-seconds: 3600

logging:
  level:
    org.hibernate.SQL: debug